### ISSUE TITLE
TimeoutException when creating table vw_offsetstore

### ISSUE THREAD

**Issue by hervandevliert** [cafienne/bounded-framework#18]
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:142)
	at io.cafienne.bounded.akka.persistence.eventmaterializers.CassandraOffsetStore.<init>(OffsetStore.scala:82)
	at io.cafienne.bounded.akka.persistence.eventmaterializers.ReadJournalOffsetStore.$init$(OffsetStore.scala:161)

**Comment by olger** [comment]
@hervandevliert this can be closed, right ?
